export { default as react } from "@/assets/images/resources/react.svg";
export { default as radius } from "@/assets/images/resources/Radius.svg";
export { default as logo } from "@/assets/images/resources/logo 1.png";
export { default as avatar } from "@/assets/images/resources/adminAvatar.png";
export { default as background } from "@/assets/images/po2final.png";
export { default as forgotPassword } from "@/assets/images/resources/ForgotPassword.gif";
export { default as enterOTP } from "@/assets/images/resources/EnterOTP.gif";
export { default as cloudy } from "@/assets/images/resources/cloudy.png";
export { default as rainy } from "@/assets/images/resources/rainy.png";
export { default as snowy } from "@/assets/images/resources/snowy.png";
export { default as sunny } from "@/assets/images/resources/sunny.png";
export { default as airQuality } from "@/assets/images/resources/air-quality.png";
export { default as boy } from "@/assets/images/resources/final-boy.jpg";
